import Pic from "@/public/Performance.png";
import Hero from "@/components/hero";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function PerformanceLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div>
      <div className="absolute w-full">
        <Hero imgUrl={Pic} altTxt="" content="Welcome to our website"></Hero>
      </div>
      {children}

    </div>

  )
}
